# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: 'Auto install k8s using sealos'
description: 'Auto install k8s using sealos'
author: 'cuisongliu'

branding:
  # https://actions-cool.github.io/github-action-branding/
  icon: 'file'
  color: 'blue'

inputs:
  type:
    description: 'Type of sealos cmd'
    required: true
    default: 'run'

  image:
    description: 'rootfs image,support docker and containerd'
    required: false
    default: "docker.io/labring/kubernetes:v1.24.0"

  sealosVersion:
    description: 'sealos release version'
    default: "4.1.3"

  buildah:
    description: 'buildah for sealos'
    default: "false"

  sealctl:
    description: 'sealctl for sealos'
    default: "false"

  debug:
    description: 'sealos run enable debug'
    default: "false"



#outputs:
#  result:
#    description: action result

runs:
  using: "composite"
  steps:
    - run: |
        sudo UseBuildah=${{ inputs.buildah }} UseSealctl=${{ inputs.sealctl }} SealosVersion=${{ inputs.sealosVersion }} make install-sealos
        sudo Image=${{ inputs.image }} Debug=${{ inputs.debug }} CmdOpts=run make cmd
      shell: bash
      id: default
