# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: 'Auto install k8s using sealos'
description: 'Auto install k8s using sealos'
author: 'cuisongliu'

branding:
  # https://actions-cool.github.io/github-action-branding/
  icon: 'file'
  color: 'blue'

inputs:
  image:
    description: 'rootfs image,support docker and containerd'
    required: true
    default: "labring/kubernetes:v1.24.0"

  sealosVersion:
    description: 'kubernetes type,support docker and containerd'
    default: "4.1.3"

  buildah:
    description: 'useBuildah for sealos'
    default: "false"

  debug:
    description: 'sealos run enable debug'
    default: "false"



#outputs:
#  result:
#    description: action result

runs:
  using: "composite"
  steps:
    - run: |
        sudo UseBuildah=${{ inputs.buildah }} SealosVersion=${{ inputs.sealosVersion }} make install-sealos
        sudo RootfsImage=${{ inputs.image }} Debug=${{ inputs.debug }} make run-k8s
      shell: bash
      id: default
