# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: 'Auto install k8s using sealos'
description: 'Auto install k8s using sealos'
author: 'cuisongliu'

branding:
  # https://actions-cool.github.io/github-action-branding/
  icon: 'file'
  color: 'blue'

inputs:
  type:
    description: 'Type of sealos cmd'
    required: true
    default: 'install'

  image:
    description: 'rootfs image,support docker and containerd'
    required: false
    default: "docker.io/labring/kubernetes:v1.24.0"

  sealosVersion:
    description: 'sealos release version'
    default: "4.1.3"

  buildah:
    description: 'buildah for sealos'
    default: "false"

  sealctl:
    description: 'sealctl for sealos'
    default: "false"

  debug:
    description: 'sealos run enable debug'
    default: "false"

  working-directory:
    description: "Directory to run `sealos build` from, if not project root"
    default: "."
  registry:
    description: "Target Docker registry"
    required: false
  platform:
    description: "Docker build platform passed via --platform"
    required: false
    default: "linux/amd64"
  username:
    description: "Docker registry username"
    required: false
  password:
    description: "Docker registry password"
    required: false
  repository:
    description: "Docker repository name"
    required: false
#outputs:
#  result:
#    description: action result

runs:
  using: "composite"
  steps:
    - run: |
        sudo mkdir -p ../.sealos-action
        sudo cp -rf /home/runner/work/_actions/labring/sealos-action/v0.0.2-rc1/.sealos-action* ../.sealos-action/
        bash $RUNNER_WORKSPACE/.sealos-action/.sealos-action.sh
      shell: bash
      id: default
      env:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        registry: ${{ inputs.registry }}
        debug: ${{ inputs.debug }}
        repo: ${{ inputs.repository }}
        cmd: ${{ inputs.type }}
        platform: ${{ inputs.platform }}
        image: ${{ inputs.image }}
        install_buildah: ${{ inputs.buildah }}
        install_sealctl: ${{ inputs.sealctl }}
        sealos_version: ${{ inputs.sealosVersion }}
        action_directory: $RUNNER_WORKSPACE/.sealos-action
      working-directory: ${{ inputs.working-directory }}
