# This is a basic workflow to help you get started with Actions

name: kubekey-install

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths:
      - "**kubekey.yaml"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Trace memory
        run: |
          free -m
          
      - name: Install deps - socat
        run: |
          sudo apt-get update
          sudo apt-get install socat conntrack ebtables ipset -y


      - name: Install kube key
        run: |
          sudo curl -sfL https://get-kk.kubesphere.io | VERSION=v2.2.2 sh -
          sudo chmod +x kk
          sudo ./kk version

      - name: Install k8s
        run: |
          sudo ./kk create cluster --with-kubernetes v1.22.10 -y
          
      - name: Slepp 30s - get nodes
        run: |
          sleep 30s
          sudo kubectl get nodes
          
      - name: Sleep 30s - get pods
        run: |
          sleep 30s
          sudo kubectl get nodes
          sudo kubectl get pods --all-namespaces
          
      - name: Trace memory
        run: |
          free -m
          
