# This is a basic workflow to help you get started with Actions

name: Sealos Install

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths:
      - "**sealos-install.yml"
      - "Makefile"
      - "**.sh"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sealos-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Trace memory
        run: |
          free -m

      - name: Install sealos version
        run: |
          sudo UseBuildah=true UseSealctl=true make install-sealos
          sudo Username= Password= Registry= make cmd

      - name: Login sealos
        run: |
          sudo Username=${{ github.repository_owner }} Password=${{ secrets.GH_TOKEN }} Registry=ghcr.io CmdOpts=login make cmd

      - name: Build sealos image
        working-directory: test/build-dockerfile
        run: |
          sudo Image=ghcr.io/${{ github.repository_owner }}/testactionimage:dockerfile CmdOpts=build make cmd
      - name: Build sealos image
        working-directory: test/build-kubefile
        run: |
          sudo Image=ghcr.io/${{ github.repository_owner }}/testactionimage:kubefile CmdOpts=build make cmd
      

      - name: Trace memory
        run: free -m
  sealos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Trace memory
        run: |
          free -m

      - name: Auto install k8s using sealos
        uses: labring/sealos-action@v0.0.1
        with:
          image: labring/kubernetes:v1.24.0
          sealosVersion: 4.1.3
          buildah: false
          debug: true
          sealctl: true

      - name: Run app image
        run:  sudo sealos run labring/helm:v3.8.2 labring/calico:v3.24.1  --debug

      - name: Trace memory
        run: free -m
