# This is a basic workflow to help you get started with Actions

name: Sealos Install By Code

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths:
      - "**sealos-install.yml"
      - "action.sh"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sealos-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Trace memory
        run: |
          free -m

      - name: Install sealos
        run: |
          sudo UseBuildah=true UseSealctl=true make -f .sealos-action-Makefile install-sealos 

      - name: Install sealos version
        run: |
          bash .sealos-action.sh

      - name: Login sealos
        run: |
          username=${{ github.repository_owner }} password=${{ secrets.GH_TOKEN }} registry=ghcr.io cmd=login bash .sealos-action.sh

      - name: Build sealos image by dockerfile
        working-directory: test/build-dockerfile
        run: |
          sudo cp ../../.sealos-action.sh .
          sudo repo=${{ github.repository_owner }} registry=ghcr.io image=testactionimage:dockerfile cmd=build bash .sealos-action.sh
      - name: Build sealos image by kubefile
        working-directory: test/build-kubefile
        run: |
          sudo cp ../../.sealos-action.sh .
          sudo repo=${{ github.repository_owner }} registry=ghcr.io image=testactionimage:kubefile cmd=build debug=true bash .sealos-action.sh

      - name: Run images
        run: |
          cmd=images debug=true bash .sealos-action.sh

      - name: Trace memory
        run: free -m
