# This is a basic workflow to help you get started with Actions

name: Sealos Install By Code

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths:
      - "**sealos-install.yml"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sealos-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Trace memory
        run: |
          free -m

      - name: Install sealos version
        run: |
          sudo UseBuildah=true UseSealctl=true make install-sealos
          bash action.sh

      - name: Login sealos
        run: |
          username=${{ github.repository_owner }} password=${{ secrets.GH_TOKEN }} registry=ghcr.io cmd=login bash action.sh

      - name: Build sealos image
        working-directory: test/build-dockerfile
        run: |
          sudo image=testactionimage:dockerfile cmd=build make cmd
      - name: Build sealos image
        working-directory: test/build-kubefile
        run: |
          sudo image=testactionimage:kubefile cmd=build debug=true make cmd
      

      - name: Trace memory
        run: free -m
