# This is a basic workflow to help you get started with Actions

name: Sealos Install

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths:
      - "**sealos-install.yml"
      - "**Makefile"
      - "**.sh"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sealos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Trace memory
        run: |
          free -m

      - name: Auto install k8s using sealos
        uses: cuisongliu/experiment-setup-k8s-in-actions@v0.0.1-rc1
        with:
          rootfsImage: labring/kubernetes:v1.24.0
          sealosVersion: 4.1.3
          useBuildah: false
          debug: true


      - name: Trace memory
        run: free -m
